### ISSUE TITLE
Import not possible

### ISSUE THREAD

**Issue by markusgumbel** [markusgumbel/moduro#13]
![2015-04-01 09_26_16-input error](https://cloud.githubusercontent.com/assets/611134/6936342/2cd9356e-d851-11e4-9c0f-63f68530efd7.png)

**Comment by markusgumbel** [comment]
Certainly a hard coded path...

**Comment by MrMorten** [comment]
old code, gonna delete it soon

**Comment by MrMorten** [comment]
Deleted import simulation and hard coded code. Simulation gets imported while saving an node.
