### ISSUE TITLE
Creation of node not possible

### ISSUE THREAD

**Issue by markusgumbel** [markusgumbel/moduro#14]
![2015-04-01 10_35_22-input error](https://cloud.githubusercontent.com/assets/611134/6937280/c666215c-d85a-11e4-846c-dd44a518595a.png)

**Comment by markusgumbel** [comment]
Probably the MetricType object is wrong?

**Comment by MrMorten** [comment]
can´t reproduce this bug, need to get the filesystem

**Comment by MrMorten** [comment]
happens if the filesystem is wrong. There now pops up an error message which tells the user which file could not be found.
